Repository eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt, pull requests merged in 2024-06, with the labels that each got.

#238 Support CWT Proofs
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/CredentialConfiguration.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/AuthorizationServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialIssuerMetadataJsonParser.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/MockData.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/PidDevIssuer.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/PidDevIssuerTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/TestableIssuer.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: feature, draft13, interoperability

#243 Support x5c to CWT Proof
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
Labels: feature, draft13

#245 More permissive CWT proof metadata validation
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialIssuerMetadataJsonParser.kt
Labels: draft13, improvement, interoperability

#247 Update CBOR lib
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilderTest.kt
Labels: dependencies

#254 Add test case to verify PID issuance in mso_mdoc format using CWT Proof against pid-issuer-srv.
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/PidDevIssuerTest.kt
Labels: feature

#255 Fix typos.
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/PidDevIssuerTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/TestableIssuer.kt
Labels: other

#257 Track expires_in for access & refresh token
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DPoPJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/AuthorizationServerClient.kt
Labels: feature

#260 QueryForDeferredCredential to support automatic refresh of access_token
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/AuthorizeIssuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/NotifyIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/QueryForDeferredCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/CredentialIssuanceRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DPoPJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/NotifyIssuerImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/QueryForDeferredCredentialImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RefreshAccessToken.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ResponseEncryption.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/AuthorizationEndpointClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialEndpointClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceRequestJsonMapper.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/NotificationEndPointClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/TokenEndpointClient.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceBatchRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceNotificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceSingleRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: feature

#263 Simplify CredentialIssuerEndpoint
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/CredentialIssuerMetadataResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialEndpointClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/NotificationEndPointClient.kt
Labels: improvement

#268 Implement DeferredIssuer
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/DeferredIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DPoPJwtFactory.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/DeferredIssuerExtensions.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: feature, draft13
