Repository eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt, pull requests merged in 2024-04, with the labels that each got.

#181 Group and limit dependabot PRs.
  .github/dependabot.yml
Labels: feature

#183 Introduce core-libs dependabot group.
  .github/dependabot.yml
Labels: feature, dependencies

#194 Fix typo Crednetial --> Credential in README.md
  README.md
Labels: documentation

#197 Optional expires_in in token response
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizationServerClient.kt
Labels: bug

#199 Mark credential_identifiers of an authorization_details as optional
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/Serialization.kt
Labels: bug

#193 Support W3C signed jwt credential requests
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/formats/CredentialIssuanceRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/formats/IssuanceRequestJsonMapper.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceAuthorizationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceBatchRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceSingleRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/TestUtils.kt
  src/test/resources/well-known/openid-credential-issuer_encrypted_responses.json
  src/test/resources/well-known/openid-credential-issuer_encryption_not_required.json
  src/test/resources/well-known/openid-credential-issuer_encryption_not_supported.json
  src/test/resources/well-known/openid-credential-issuer_no_scopes.json
Labels: feature

#201 Add locations to authorization_details
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizationServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
Labels: bug

#191 Add support for DPoP
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizationServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DPoPJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DefaultAuthorizationServerMetadataResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/IssuanceServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/DelegatingProofSigner.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
Labels: feature

#207 Add missing check of the state returned by auth. server
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceAuthorizationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/TestUtils.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: bug, feature

#210 Verify that the Proof signing algorithm is supported by the issuer.
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilderTest.kt
Labels: feature, draft13

#211 Update gradle action
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dependencies, github_actions
