Repository eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt, pull requests merged in 2024-07, with the labels that each got.

#273 Improve credential request ergonomics
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceBatchRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceNotificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceSingleRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/TestUtils.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: improvement

#277 Add a factory method for Issuer for wallet-initiated case
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: improvement

#279 Fix generic tests to use improved Issuer API for automatic invalid_proof handling
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
Labels: bug

#272 Document library usages as "use - cases"
  README.md
Labels: documentation, improvement

#283 Externalize issuer's dPoPJwtFactory
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/DPoP.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/DeferredIssuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/NotificationEndPointClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/TokenEndpointClient.kt
Labels: improvement

#285 Fix proof generation on tests
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
Labels: bug

#286 Upgrade to gradlew 8.9
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#287 Remove deprecated code
  README.md
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceBatchRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceNotificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceSingleRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: improvement
