Repository eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt, pull requests merged in 2024-05, with the labels that each got.

#212 Reorganize OAUTH2 & Credential Issuer HTTP clients
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/CredentialIssuanceRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DefaultCredentialIssuerMetadataResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/IssuanceServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/NotifyIssuerImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/QueryForDeferredCredentialImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ResponseEncryption.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/formats/IssuanceRequestJsonMapper.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/AuthorizationServerClient.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialIssuerMetadataJsonParser.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceRequestJsonMapper.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceServerClient.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceAuthorizationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceBatchRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceNotificationTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceSingleRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/RequestMockers.kt
Labels: feature

#215 Make credential offer available from Issuer
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
Labels: feature

#219 Add logging to examples
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: feature

#223 Batch issuance response encryption
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/CredentialIssuanceRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceRequestJsonMapper.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceServerClient.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: feature, draft13

#228 Fix authorization server metadata resolution
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DefaultAuthorizationServerMetadataResolver.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/DefaultAuthorizationServerMetadataResolverTest.kt
Labels: bug

#226 Deferred response encryption
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceRequestJsonMapper.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/IssuanceServerClient.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceDeferredRequestTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/IssuanceEncryptedResponsesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/RequestMockers.kt
Labels: feature, draft13

#229 Improve Proof Types Supported
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/CredentialConfiguration.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizeIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/http/CredentialIssuerMetadataJsonParser.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/MockData.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilderTest.kt
Labels: improvement

#231 Deprecate ProofSigner & BindingKey
  build.gradle.kts
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DPoPJwtFactory.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilderTest.kt
Labels: improvement

#233 Fix Proof Serialization Bug
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/Serialization.kt
Labels: bug

#235 Improve examples
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuance.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/CryptoGenerator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/OfferBasedIssuanceUsingPreAuthorizationFlow.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt
Labels: improvement

#236 Refactor ProofBuilder
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/Proof.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilder.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vci/internal/ProofBuilderTest.kt
Labels: improvement
